const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
    await page.waitForTimeout(400);
    await page.locator('#toggleRun').click();
    assert.equal(await page.locator('#statusText').textContent(), '仿真已暂停');
    const clock = await page.locator('#clock').textContent();
    await page.waitForTimeout(200);
    assert.equal(await page.locator('#clock').textContent(), clock);
    await page.locator('#reset').click();
    assert.equal(await page.locator('#clock').textContent(), '00:00.0');
    assert.equal(await page.locator('#outerAngle').textContent(), '25.0°');
    assert.equal(await page.locator('#coverageValue').textContent(),'0.00%');
    assert.equal(await page.locator('#viewGravityResult').isDisabled(),true);
    await page.screenshot({ path: path.join(__dirname, 'preview.png'), fullPage: true });
    await page.locator('#randomMode').click();
    assert.equal(await page.locator('#randomControls').isVisible(), true);
    assert.equal(await page.locator('#uniformControls').isVisible(), false);
    await page.locator('#reset').click();
    assert.equal(await page.locator('#outerActual').textContent(), '0.000 rpm');
    assert.equal(await page.locator('#interval').count(),0);
    assert.equal(await page.locator('#residualGravity').textContent(),'— g');
    await page.locator('#outerMaxInput').fill('1.25');
    assert.equal(await page.locator('#outerMax').inputValue(),'1.25');
    await page.locator('#innerMax').fill('3.5');
    assert.equal(await page.locator('#innerMaxInput').inputValue(),'3.5');
    await page.locator('#innerMaxInput').fill('2.75');
    assert.equal(await page.locator('#innerMax').inputValue(),'2.75');
    await page.locator('#outerMaxInput').fill('0');
    assert.equal(await page.locator('#outerMaxError').isVisible(),true);
    await page.locator('#outerMaxInput').fill('1.25');
    assert.equal(await page.locator('#outerMaxError').isVisible(),false);
    await page.locator('#acceleration').fill('0.02');
    assert.ok((await page.locator('#chartNote').textContent()).includes('0.02 rpm/s'));
    await page.locator('#acceleration').fill('0');
    assert.equal(await page.locator('#accelerationError').isVisible(),true);
    await page.locator('#acceleration').fill('0.02');
    assert.equal(await page.locator('#accelerationError').isVisible(),false);
    await page.locator('#toggleRun').click();
    await page.waitForTimeout(700);
    await page.locator('#toggleRun').click();
    assert.notEqual(await page.locator('#outerActual').textContent(), '0.000 rpm');
    const speed=Math.abs(Number((await page.locator('#outerActual').textContent()).replace(' rpm','').replace('−','-')));
    const duration=Number((await page.locator('#gravityDuration').textContent()).match(/[\d.]+/)[0]);
    assert.ok(Math.abs(speed-.02*duration)<.002,'Entered acceleration must affect actual speed');
    await page.locator('#uniformMode').click();
    await page.locator('#outerSpeedInput').fill('1.2345');
    assert.equal(await page.locator('#outerActual').textContent(),'1.234 rpm');
    await page.locator('#outerSpeedInput').fill('11');
    assert.equal(await page.locator('#outerSpeedError').isVisible(),true);
    assert.equal(await page.locator('#outerActual').textContent(),'1.234 rpm');
    await page.locator('#outerSpeedInput').fill('0');
    assert.equal(await page.locator('#outerSpeedError').isVisible(),false);
    await page.locator('#innerSpeedInput').fill('-5');
    assert.equal(await page.locator('#innerSpeed').inputValue(),'-5');
    await page.locator('#outerSpeed').fill('0');
    await page.locator('#innerSpeed').fill('-5');
    assert.equal(await page.locator('#outerActual').textContent(), '0.000 rpm');
    assert.equal(await page.locator('#innerActual').textContent(), '−5.000 rpm');
    await page.locator('#outerSpeed').fill('1');
    assert.equal(await page.locator('#outerSpeedInput').inputValue(),'1');
    await page.locator('#innerSpeed').fill('2');
    await page.locator('#reset').click();
    await page.locator('#fastForward').click();
    await page.waitForFunction(()=>document.getElementById('gravityDuration').textContent==='累计 600.0 s');
    await page.waitForFunction(()=>!document.getElementById('fastForward').disabled);
    assert.equal(await page.locator('#gravityStatus').textContent(),'平均指标达标');
    assert.equal(await page.locator('#statusText').textContent(),'仿真已暂停');
    assert.equal(await page.locator('#coverageSamples').textContent(),'12,000');
    assert.ok(Number((await page.locator('#coverageMinCount').textContent()).replace(/[^\d]/g,''))>0);
    assert.ok((await page.locator('#coverageScaleNote').textContent()).includes('线性映射'));
    assert.ok(Number((await page.locator('#coverageValue').textContent()).replace('%',''))>0);
    const frozenCoverage=await page.locator('#coverageCells').textContent();
    await page.waitForTimeout(100);assert.equal(await page.locator('#coverageCells').textContent(),frozenCoverage);
    await page.locator('#coverageMap').scrollIntoViewIfNeeded();
    const map=await page.locator('#coverageMap').boundingBox();
    await page.mouse.move(map.x+map.width/2,map.y+map.height/2);
    assert.ok((await page.locator('#coverageMapReadout').textContent()).includes('次采样'));
    await page.locator('#coverageSphere').scrollIntoViewIfNeeded();
    const sphere=await page.locator('#coverageSphere').boundingBox();
    await page.mouse.move(sphere.x+sphere.width/2,sphere.y+sphere.height/2);
    assert.ok((await page.locator('#coverageSphereReadout').textContent()).includes('次采样'));
    const beforeRotation=await page.locator('#coverageSphere').evaluate(el=>el.toDataURL());
    await page.mouse.down();await page.mouse.move(sphere.x+sphere.width/2+80,sphere.y+sphere.height/2+15,{steps:8});await page.mouse.up();
    assert.notEqual(await page.locator('#coverageSphere').evaluate(el=>el.toDataURL()),beforeRotation);
    assert.equal(await page.locator('#coverageCells').textContent(),frozenCoverage,'Rotating the view must not change coverage');
    await page.locator('#resetSphereView').click();
    assert.equal(await page.locator('#coverageSphere').evaluate(el=>el.toDataURL()),beforeRotation);
    await page.locator('.coverage-panel').screenshot({path:path.join(__dirname,'preview-coverage.png')});
    await page.locator('.component-panel').screenshot({path:path.join(__dirname,'preview-components.png')});
    const componentsEvent=page.waitForEvent('download');await page.locator('#exportComponentsPng').click();
    const componentsDownload=await componentsEvent;await componentsDownload.saveAs(path.join(__dirname,'export-components-preview.png'));
    const componentsPng=fs.readFileSync(path.join(__dirname,'export-components-preview.png'));assert.equal(componentsPng.readUInt32BE(16),1800);assert.equal(componentsPng.readUInt32BE(20),1600);
    await page.locator('#instantTimeWindow').selectOption('600');await page.locator('#meanTimeWindow').selectOption('60');await page.locator('#meanAxisScale').selectOption('auto');
    await page.locator('#gravityTimeWindow').selectOption('60');
    await page.locator('#gravityAxisScale').selectOption('auto');
    assert.ok((await page.locator('#gravityPlotSummary').textContent()).includes('540.0～600.0'));
    await page.locator('#viewGravityResult').click();
    assert.equal(await page.locator('#gravityResultDialog').isVisible(),true);
    assert.ok((await page.locator('#gravityResultSummary').textContent()).includes('600.0'));
    await page.waitForFunction(()=>document.getElementById('gravityResultImage').naturalWidth===1800);
    const pngEvent=page.waitForEvent('download');await page.locator('#resultExportPng').click();
    const pngDownload=await pngEvent;await pngDownload.saveAs(path.join(__dirname,'export-preview.png'));
    const png=fs.readFileSync(path.join(__dirname,'export-preview.png'));assert.equal(png.readUInt32BE(16),1800);assert.equal(png.readUInt32BE(20),1120);
    const csvEvent=page.waitForEvent('download');await page.locator('#resultExportCsv').click();
    const csvDownload=await csvEvent;await csvDownload.saveAs(path.join(__dirname,'export-preview.csv'));
    const rows=fs.readFileSync(path.join(__dirname,'export-preview.csv'),'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/);
    assert.ok(rows[0].includes('累计平均矢量的模(g)'));assert.ok(rows.length>=1201);
    assert.equal(Number(rows[1].split(',')[0]),.1);assert.equal(Number(rows[rows.length-1].split(',')[0]),600);
    assert.ok(rows.every(row=>row.split(',').length===20));
    for(const row of rows.slice(1)){
      const values=row.split(',').map(Number);
      assert.ok(Math.abs(Math.hypot(...values.slice(5,8))-1)<1e-8,'Exported instantaneous gravity has unit norm');
      assert.ok(Math.abs(Math.hypot(...values.slice(2,5))-values[1])<1e-8,'Exported mean components match residual norm');
    }
    await page.locator('#gravityResultDialog form button').click();
    assert.equal(await page.locator('#gravityResultDialog').isVisible(),false);
    assert.equal(await page.locator('#statusText').textContent(),'仿真已暂停');
    for(let i=0;i<5;i++){
      await page.locator('#fastForward').click();
      await page.waitForFunction(()=>!document.getElementById('fastForward').disabled);
    }
    assert.equal(await page.locator('#gravityDuration').textContent(),'累计 3600.0 s');
    await page.locator('#gravityTimeWindow').selectOption('0');await page.locator('#gravityAxisScale').selectOption('fixed');
    const fullCount=Number((await page.locator('#gravityPlotSummary').textContent()).match(/· ([\d,]+) 个记录点/)[1].replaceAll(',',''));
    assert.ok(fullCount>=7200,'Long runs must retain every recorded point');
    await page.locator('.gravity-panel').screenshot({path:path.join(__dirname,'preview-long-curve.png')});
    await page.locator('#partialPreset').selectOption('0.165');await page.locator('#applyPartialGravity').click();
    assert.equal(await page.locator('#gravityDuration').textContent(),'累计 0.0 s');
    assert.equal(await page.locator('#outerSpeedInput').inputValue(),'0');assert.equal(await page.locator('#innerSpeedInput').inputValue(),'2');
    assert.ok((await page.locator('#partialPlanSummary').textContent()).includes('0.165 g'));
    assert.equal(await page.locator('#targetEvaluation').inputValue(),'match');assert.equal(await page.locator('#instantGravityMagnitude').textContent(),'1 g');
    assert.equal(await page.locator('#worldGravityVector').textContent(),'(0, −1, 0) g');
    await page.locator('[data-view="front"]').click();
    await page.locator('.scene-panel').screenshot({path:path.join(__dirname,'preview-world-gravity.png')});
    await page.locator('#showWorldGravity').uncheck();assert.equal(await page.locator('#showWorldGravity').isChecked(),false);
    await page.locator('#showWorldGravity').check();
    await page.locator('#fastForward').click();await page.waitForFunction(()=>!document.getElementById('fastForward').disabled);
    assert.ok(Math.abs(Number((await page.locator('#residualGravity').textContent()).replace(' g',''))-.165)<1e-6);
    assert.equal(await page.locator('#gravityStatus').textContent(),'平均指标达标');
    await page.locator('#targetGravity').fill('0.378');assert.equal(await page.locator('#partialPreset').inputValue(),'');
    assert.equal(await page.locator('#gravityStatus').textContent(),'平均指标未达标','A lower residual is not a match to Mars gravity');
    await page.locator('#applyPartialGravity').click();await page.locator('#fastForward').click();await page.waitForFunction(()=>!document.getElementById('fastForward').disabled);
    assert.ok(Math.abs(Number((await page.locator('#residualGravity').textContent()).replace(' g',''))-.378)<1e-6);
    await page.locator('.gravity-panel').screenshot({path:path.join(__dirname,'preview-partial-gravity.png')});
    const partialCsvEvent=page.waitForEvent('download');await page.locator('#exportGravityCsv').click();const partialCsv=await partialCsvEvent;
    await partialCsv.saveAs(path.join(__dirname,'export-partial-preview.csv'));
    const partialValues=fs.readFileSync(path.join(__dirname,'export-partial-preview.csv'),'utf8').trim().split(/\r?\n/).at(-1).split(',');
    assert.equal(Number(partialValues[16]),1);assert.equal(Number(partialValues[17]),.378);assert.equal(partialValues[18],'接近目标');
    await page.locator('#partialPreset').selectOption('0.001');await page.locator('#applyPartialGravity').click();
    assert.ok(Math.abs(Number(await page.locator('#targetTolerance').inputValue())-.00005)<1e-10);
    await page.locator('#targetGravity').fill('1.5');await page.locator('#applyPartialGravity').click();
    assert.equal(await page.locator('#targetGravityError').isVisible(),true);
    assert.equal(await page.locator('#outerSpeedInput').inputValue(),'0');
    await page.locator('#targetGravity').fill('.378');await page.locator('#applyPartialGravity').click();
    await page.locator('#environmentPreset').selectOption('0.165');
    assert.equal(await page.locator('#gravityDuration').textContent(),'累计 0.0 s');assert.equal(await page.locator('#instantGravityMagnitude').textContent(),'0.165 g');
    assert.equal(await page.locator('#worldGravityVector').textContent(),'(0, −0.165, 0) g');
    await page.locator('#environmentGravity').fill('2');await page.locator('#environmentGravity').press('Tab');
    assert.equal(await page.locator('#instantGravityMagnitude').textContent(),'2 g');assert.ok((await page.locator('#gravityAxisScale option').first().textContent()).includes('2 g'));
    await page.locator('#restoreDualAxis').click();assert.equal(await page.locator('#instantGravityMagnitude').textContent(),'1 g');assert.equal(await page.locator('#outerAngle').textContent(),'25.0°');
    await page.locator('#randomMode').click();
    await page.screenshot({ path: path.join(__dirname, 'preview-random.png'), fullPage: true });
    await page.locator('#timeScale').fill('7.5');
    assert.equal(await page.locator('#timeScaleValue').textContent(), '7.5×');
    assert.equal(await page.locator('#timeScalePreset').inputValue(),'');
    await page.locator('#timeScale').fill('0');
    assert.equal(await page.locator('#timeScaleValue').textContent(), '7.5×');
    assert.equal(await page.locator('#timeScaleError').isVisible(),true);
    await page.locator('#timeScale').fill('1001');
    assert.equal(await page.locator('#timeScaleValue').textContent(), '7.5×');
    await page.locator('#timeScale').fill('0.01');
    assert.equal(await page.locator('#timeScaleValue').textContent(), '0.01×');
    assert.equal(await page.locator('#timeScaleError').isVisible(),false);
    await page.locator('#timeScalePreset').selectOption('1000');
    assert.equal(await page.locator('#timeScaleValue').textContent(), '1000×');
    assert.equal(await page.locator('#timeScale').inputValue(),'1000');
    await page.locator('#reset').click();
    assert.equal(await page.locator('#coverageValue').textContent(),'0.00%');
    assert.equal(await page.locator('#coverageSamples').textContent(),'0');
    await page.locator('#toggleRun').click();
    await page.waitForTimeout(250);
    await page.locator('#toggleRun').click();
    const simulatedSeconds=Number((await page.locator('#gravityDuration').textContent()).match(/[\d.]+/)[0]);
    assert.ok(simulatedSeconds>10,'Custom speed must advance simulation time');
    await page.locator('#timeScale').fill('4');
    await page.locator('[data-view="top"]').click();
    await page.locator('.scene-panel').screenshot({path:path.join(__dirname,'preview-world-gravity-top.png')});
    assert.equal(await page.locator('[data-view="top"]').getAttribute('aria-pressed'), 'true');
    await page.locator('#showAxes').uncheck();
    await page.locator('#showTrail').uncheck();
    await page.locator('#resetView').click();
    assert.equal(await page.locator('[data-view="iso"]').getAttribute('aria-pressed'), 'true');
    await page.setViewportSize({ width: 375, height: 812 });
    await page.waitForTimeout(150);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile viewport must not overflow horizontally');
    await page.screenshot({ path: path.join(__dirname, 'preview-mobile.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('Passed: partial-gravity presets/custom target, match evaluation, invalid target validation, environmental gravity and CSV metadata, restore dual-axis plan, numeric controls, long-run retention, curves and exports, sphere interaction, mobile layout and no browser errors.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
